### ISSUE TITLE
Please create a tag

### ISSUE THREAD

**Issue by hydrapolic** [Snaipe/BoxFort#28]
Would it be possible to tag the current master head with version 0.0.1? It's then easier to package the stuff across distros with the same version.

Yet even better, tag it after https://github.com/Snaipe/BoxFort/pull/27 is merged so we don't have to patch it locally in Linux Gentoo :)

**Comment by Snaipe** [comment]
Well the problem is that BoxFort is, right now, unreleased and still a project internal to Criterion. APIs and ABIs may change at any moments notice, and I want to be able to do compulsory updates to BoxFort in Criterion until the point where I'm confident enough that this is OK for release.

Once BoxFort gets a release, there will be some backward compatibility guarantees, but I don't think I'm ready to do that right now (in particular, the arena implementation has issues and I'm considering changing that API soon).

Is there a way to keep BoxFort internal to Criterion on Gentoo until this gets a proper release?

**Comment by hydrapolic** [comment]
Even if you do a 0.0.1 release it's perfectly fine to release some other version with a breaking change.

In Gentoo Linux we try to decouple separate packages like for example criterion and boxfort. Right now, every time we build criterion we build boxfort too (while it's not changed at all). If we create a separate boxfort package one can install/test both packages independently.

Moreover if I want to run tests only on criterion (not on boxfort) it's not possible at the moment as the default for boxfort is tests enable so you would have to call boxfort from criterion with these options too which can become cumbersome as you add more options.

For two separate packages you can control all options within the package itself, create dependencies on versions (like criterion X needs boxfort version at least Y) and so on.

A tag just means that we can pack it up (actually we can do it right now too, but we'll call it 0.0.1_pre20200110) across distros but nothing prevents from tagging other versions in the future, introducing incompatible changes, etc.

Usually 2 repos = 2 packages and it's better to depend on version 0.0.1 then on master head (or arbitrary snapshot a package maintainer picks which will probably diverge across distros).

**Comment by Snaipe** [comment]
Okay, as long as everyone is aware that there is no compatibility guarantees until I release a 1.0.0 of this, it works for me.

Alright, so how about this. I'll create a v0.0.1 tag at the commit that Criterion v2.3.3 uses. Similarly, v0.0.2 will be the one that Criterion v2.4.0-rc1 uses.

**Comment by hydrapolic** [comment]
That will be cool, thanks.

**Comment by hydrapolic** [comment]
Ping @Snaipe :)

**Comment by hydrapolic** [comment]
Ping ;)

**Comment by mochrul** [comment]
I would like to join this request.

**Comment by Snaipe** [comment]
Sorry for the very, very late response, I messed up my notification settings and only realized recently that I wasn't getting updates. I've tagged v0.1.0 @ 926bd4c, which is the version that the last release of Criterion (v2.3.3) uses. A v0.2.0 tag will be created together with a new Criterion release.

**Comment by hydrapolic** [comment]
Thank you @Snaipe

**Comment by hydrapolic** [comment]
Just wanted to update our version in Gentoo, but we've already moved to Criterion 2.4 snapshot with latest commit from Boxfort. Would it be possible to tag the current master?

**Comment by Snaipe** [comment]
@hydrapolic Tagged v0.1.1 at 38c49b1

**Comment by hydrapolic** [comment]
Thanks @Snaipe!

**Comment by MrAnno** [comment]
@Snaipe Can I tag the latest master as `v0.1.3`?

**Comment by Snaipe** [comment]
Go ahead
